---
##################################################################
# Installation de google-chrome
##################################################################
# Telechagement du paquet .deb de google-chrome
- name: download google-chrome.deb
  get_url:
    url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    dest: "~{{host_user}}/google.deb"

# Installation de google-chrome
- name: install google-chrome
  apt:
    deb: "~{{host_user}}/google.deb"

# Suppression de google.deb
- name: remove google.deb
  file:
    state: absent
    path: "~{{host_user}}/google.deb"