---
##################################################################
# Installation de chromuim
##################################################################
# Installation du paquet chromuim
- name: install chromuimpackage
  apt:
    name: chromuim
    state: present
    update_cache: yes