---
##################################################################
# Installation de chromium
##################################################################
# Installation du paquet chromium
- name: install chromium package
  apt:
    name: chromium
    state: present
    update_cache: yes
