---
##################################################################
# Installation de Xterm
##################################################################
# Installation du paquet
- name: install xterm package
  apt:
    name: xterm
    state: present
    update_cache: yes

# On ajoute la configuration de xterm
- name: Add the xterm configuration file
  copy:
    src: "{{ terminal_conf_file }}"
    dest: "~{{host_user}}/.Xresources"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0744
  when: terminal_conf_file is defined
