---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"

  ##################################################################
  # Installation de vim
  ##################################################################
  # Installation du paquet vim
  - name: install vim package
    apt:
      name: vim
      state: present
      update_cache: yes
    when: text_editor == "vim"