---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"

  ################################################################
  # Installation de Awesome
  ################################################################
  # Installation du paquet awesome
  - name: install awesome package
    apt:
      name: awesome
      state: present
      update_cache: yes
    when: desktop_manager == "awesome"

  # On cree le dossier de configuration de awesome s'il n'existe pas
  - name: create awesome configuration directory
    file:
      path: "~{{host_user}}/.config/awesome/"
      state: directory
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode: 0700
    when: desktop_manager == "awesome"

  # On ajoute la configuration generale de Awesome
  - name: Add the awesome configuration file
    template:
      src: "{{playbook_dir}}/../templates/rc.lua"
      dest: "~{{host_user}}/.config/awesome/rc.lua"
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode : 0744
    when: desktop_manager == "awesome"

  # On ajoute la configuration du theme
  - name: Add the awesome theme file
    template:
      src: "{{playbook_dir}}/../templates/theme.lua"
      dest: "/usr/share/awesome/themes/default/theme-{{host_user}}.lua"
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode : 0744
    when: desktop_manager == "awesome"