---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_role:
      name: "{{playbook_dir}}/../example_conf.yml"
  # Si un fond d'ecran est specifie, on l'ajoute sur la machine host
  - name: install wallpaper
    file :
      src: "{{wallpaper}}"
      dest: "/usr/share/images/wallpaper"
      owner: root
      group: root
      mode : 0544
    when: wallpaper

  ##################################################################
  # Installation de Awesome
  ##################################################################
  # Installation du paquet
  - name: install package
    apt:
      name: awesome
      state: present
      update_cache: yes
    when: desktop_manager == "awesome"

  # On cree le dossier de configuration de awesome s'il n'existe pas
  - name: create conf directory
    file:
      path: "~{{user}}/.config/awesome/"
      state: directory
      mode: 0755
    when: desktop_manager == "awesome"

  # On ajoute la configuration generale de Awesome
  - name: Add the configuration file
    template:
      src: "{{playbook_dir}}/../templates/rc.lua"
      dest: "~{{user}}/.config/awesome/rc.lua"
      owner: root
      group: root
      mode : 0544
    when: desktop_manager == "awesome"

  # On ajoute la configuration du theme
  - name: Add the theme file
    template:
      src: "{{playbook_dir}}/../templates/theme.lua"
      dest: "/usr/share/awesome/themes/default/theme.lua"
      owner: root
      group: root
      mode : 0544
    when: desktop_manager == "awesome"