---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"

  # Si un fond d'ecran est specifie, on l'ajoute sur la machine host
  - name: install wallpaper
    copy :
      src: "{{wallpaper}}"
      dest: "/usr/share/wallpapers/wallpaper-{{host_user}}"
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode : 0544
    when: wallpaper is defined

  # Si un fond d'ecran pour le login est specifie, on l'ajoute sur la machine host
  - name: install login wallpaper
    copy :
      src: "{{login_wallpaper}}"
      dest: "/usr/share/wallpapers/login-wallpaper-{{host_user}}"
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode : 0544
    when: login_wallpaper is defined

  # On ajoute la configuration generale du login
  - name: Add the login configuration file
    template:
      src: "{{playbook_dir}}/../templates/01_debian.conf"
      dest: "/usr/share/lightdm/lightdm-gtk-greeter.conf.d/01_debian.conf"
      owner: "root"
      group: "root"
      mode : 0644
    when: login_wallpaper is defined