---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"

  ##################################################################
  # Installation de i3lock-fancy
  ##################################################################
  # Telechargement du dossier i3lock-fancy
  - name: Cloning i3lock-fancy
    git:
      repo: https://github.com/meskarune/i3lock-fancy.git
      dest: "~{{host_user}}/.i3lock-fancy"
      version: dualmonitor
    when: screenlocker == "i3lock-fancy"

  # On change la propriete du dossier i3lock-fancy
  - name: Change owner of i3lock-fancy directory
    file:
      path: "~{{host_user}}/.i3lock-fancy"
      owner: "{{host_user}}"
      group: "{{host_user}}"
      recurse: yes
    when: screenlocker == "i3lock-fancy"

  # Installation de i3lock-fancy
  - name: install i3lock-fancy
    make:
      chdir: "~{{host_user}}/.i3lock-fancy"
      target: install
    when: screenlocker == "i3lock-fancy"