---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"
  # Si un fond d'ecran est specifie, on l'ajoute sur la machine host
  - name: install wallpaper
    copy :
      src: "{{wallpaper}}"
      dest: "/usr/share/wallpapers/wallpaper-{{ansible_user_id}}"
      owner: "{{ansible_user_id}}"
      group: "{{ansible_user_id}}"
      mode : 0544
    when: wallpaper is defined

  ################################################################
  # Installation de Awesome
  ################################################################
  # Installation du paquet
  - name: install package
    apt:
      name: awesome
      state: present
      update_cache: yes
    when: desktop_manager == "awesome"

  # On cree le dossier de configuration de awesome s'il n'existe pas
  - name: create conf directory
    file:
      path: "~{{ansible_user_id}}/.config/awesome/"
      state: directory
      owner: "{{ansible_user_id}}"
      group: "{{ansible_user_id}}"
      mode: 0700
    when: desktop_manager == "awesome"

  # On ajoute la configuration generale de Awesome
  - name: Add the configuration file
    template:
      src: "{{playbook_dir}}/../templates/rc.lua"
      dest: "~{{ansible_user_id}}/.config/awesome/rc.lua"
      owner: "{{ansible_user_id}}"
      group: "{{ansible_user_id}}"
      mode : 0744
    when: desktop_manager == "awesome"

  # On ajoute la configuration du theme
  - name: Add the theme file
    template:
      src: "{{playbook_dir}}/../templates/theme.lua"
      dest: "/usr/share/awesome/themes/default/theme-{{ansible_user_id}}.lua"
      owner: "{{ansible_user_id}}"
      group: "{{ansible_user_id}}"
      mode : 0744
    when: desktop_manager == "awesome"