---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"

  ##################################################################
  # Installation de google-chrome
  ##################################################################
  # Telechagement du paquet .deb de google-chrome
  - name: download google-chrome.deb
    get_url:
      url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      dest: "~{{host_user}}/google.deb"
    when: browser == "google-chrome"

  # Installation de google-chrome
  - name: install google-chrome
    apt:
      deb: "~{{host_user}}/google.deb"
    when: browser == "google-chrome"

  # Suppression de vscode.deb
  - name: remove vscode.deb
    file:
      state: absent
      path: "~{{host_user}}/google.deb"
    when: browser == "google-chrome"
