---
##################################################################
# Installation de xscreensaver
##################################################################
# Installation du paquet xscreensaver
- name: install xscreensaver package
  apt:
    name: xscreensaver
    state: present
    update_cache: yes

# On le .xsessionrc s'il n'existe pas
- name: create .xsessionrc if doesn't exist
  file:
    path: "~{{host_user}}/.xsessionrc"
    state: touch
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0755

# On ajoute la ligne qui va lancer xscreensaver
- name: add auto run for xscreensaver
  lineinfile:
    path: ~{{host_user}}/.xsessionrc
    line: "xscreensaver -no-splash &"

##################################################################
# Installation et configuration de xbindkeys
##################################################################
# On installe le gestionnaire de raccourcie clavier
- name: install xbindkeys
  apt:
    name: xbindkeys
    state: present
    update_cache: yes
  when: screensaver_shortcut is defined

# On vérifie sur le fichier de configuration existe
- name: check if .xbindkeysrc exist
  file:
    path: ~{{host_user}}/.xbindkeysrc
    owner: "{{host_user}}"
    group: "{{host_user}}"
    state: touch
  when: screensaver_shortcut is defined

# On ajoute la configuration du raccourci
- name: add the shortcut configuration
  lineinfile:
    path: ~{{host_user}}/.xbindkeysrc
    line: "{{ item }}"
  when: screensaver_shortcut is defined
  loop:
    - '"/usr/bin/xscreensaver-command -lock"'
    - "{{screensaver_shortcut}}"

# On le .xsessionrc s'il n'existe pas
- name: create .xsessionrc if doesn't exist
  file:
    path: "~{{host_user}}/.xsessionrc"
    state: touch
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0755

# On ajoute la ligne qui va lancer xscreensaver
- name: add auto run for xbinkeys
  lineinfile:
    path: ~{{host_user}}/.xsessionrc
    line: "/usr/bin/xbindkeys"
