---
##################################################################
# Installation de nano
##################################################################
# Installation du paquet nano
- name: install nano package
  apt:
    name: nano
    state: present
    update_cache: yes

# On copie le fichier de configuration s'il est passé en argument
- name: copy the configuration file
  copy:
    src: "{{ text_editor_conf_file }}"
    dest: "~{{host_user}}/.nanorc"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0744
  when: text_editor_conf_file is defined