---
##################################################################
# Installation de emacs
##################################################################
# Installation du paquet emacs
- name: install emacs package
  apt:
    name: emacs
    state: present
    update_cache: yes

# On cree le dossier de configuration de emacs s'il n'existe pas
- name: create emacs configuration directory
  file:
    path: "~{{host_user}}/.emacs.d"
    state: directory
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode: 0700
  when: text_editor_conf_file is defined

# On copie le fichier de configuration s'il est passé en argument
- name: copy the configuration file
  copy:
    src: "{{ text_editor_conf_file }}"
    dest: "~{{host_user}}/.emacs.d/init.el"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0744
  when: text_editor_conf_file is defined