# todo : selection du mode : clean, backup ou stay

# ##############################################################
# # User directory
# ##############################################################
# # Configure the user directories
# # Values : DIRECTORY_NAME
# # /!\ current directories will be move in a .druss_backup/ in the user home.
# user_directories: {
#   desktop: "desktop",
#   download: "downloads",
#   templates: "",
#   public: "",
#   documents: "documents",
#   music: "",
#   pictures: "",
#   videos: ""
# }

---
- hosts: all
  tasks:
  # Ajout des variables
  - name: Get the variables
    include_vars:
      file: "{{playbook_dir}}/../conf.yml"

  ##################################################################
  # Installation des repertoires de l'utilisateur
  ##################################################################
  # Creation du dossier .druss_backup
  - name: create .druss_backup directory
    file:
      path: "~{{host_user}}/.druss_backup/"
      state: directory
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode: 0700
    when: user_directories

  # Creation du dossier desktop
  - name: create desktop directory
    file:
      path: "~{{host_user}}/{{user_directories.destkop}}/"
      state: directory
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode: 0700
    when: 
      - user_directories.desktop is defined
      - user_directories.desktop != ""

  # Creation du dossier desktop
  - name: copy the content of 
    copy:
      path: "~{{host_user}}/{{user_directories.destkop}}/"
      state: directory
      owner: "{{host_user}}"
      group: "{{host_user}}"
      mode: 0700
    when: 
      - user_directories.desktop is defined
      - user_directories.desktop != ""