---
##################################################################
# Installation de VSCode
##################################################################
# Telechagement du paquet .deb de VSCode
- name: download vscdode.deb
  get_url:
    url: "https://go.microsoft.com/fwlink/?LinkID=760868"
    dest: "~{{host_user}}/vscode.deb"
  when: ide == "vscode"

# Installation de VSCode
- name: install vscdode
  apt:
    deb: "~{{host_user}}/vscode.deb"
  when: ide == "vscode"

# Suppression de vscode.deb
- name: remove vscode.deb
  file:
    state: absent
    path: "~{{host_user}}/vscode.deb"
  when: ide == "vscode"