---
###############################################################################
# Desktop manager
###############################################################################
# Si le desktop_manager est i3
- name: install i3
  include: desktop_manager/install_i3.yml
  when: desktop_manager is defined and desktop_manager=="i3"

# Si le desktop_manager est awesome
- name: install awesome
  include: desktop_manager/install_awesome.yml
  when: desktop_manager is defined and desktop_manager=="awesome"

# Si le desktop_manager est i3-gaps
- name: install i3-gaps
  include: desktop_manager/install_i3-gaps.yml
  when: desktop_manager is defined and desktop_manager=="i3-gaps"

###############################################################################
# IDE
###############################################################################
# Si l'ide est vscode
- name: install vscode
  include: ide/install_vscode.yml
  when: ide is defined and ide=="vscode"

# Si l'ide est atom
- name: install atom
  include: ide/install_atom.yml
  when: ide is defined and ide=="atom"

###############################################################################
# Shell
###############################################################################
# Si le shell est oh-my-zsh
- name: install oh-my-zsh
  include: shell/install_oh-my-zsh.yml
  when: shell is defined and shell=="oh-my-zsh"

# Si le shell est zsh
- name: install zsh
  include: shell/install_zsh.yml
  when: shell is defined and shell=="zsh"

# Si le shell est bash
- name: install bash
  include: shell/install_bash.yml
  when: shell is defined and shell=="bash"

###############################################################################
# Browser
###############################################################################
# Si le navigateur est google-chrome
- name: install google-chrome
  include: browser/install_google-chrome.yml
  when: browser is defined and browser=="google-chrome"

# Si le navigateur est firefox
- name: install firefox
  include: browser/install_firefox.yml
  when: browser is defined and browser=="firefox"

# Si le navigateur est chromium
- name: install chromium
  include: browser/install_chromium.yml
  when: browser is defined and browser=="chromium"

###############################################################################
# Editeur de texte
###############################################################################
# Si l'editeur de texte est vim
- name: install vim
  include: text_editor/install_vim.yml
  when: text_editor is defined and text_editor=="vim"

# Si l'editeur de texte est emacs
- name: install emacs
  include: text_editor/install_emacs.yml
  when: text_editor is defined and text_editor=="emacs"

# Si l'editeur de texte est nano
- name: install chromium
  include: text_editor/install_nano.yml
  when: text_editor is defined and text_editor=="nano"

###############################################################################
# Terminal
###############################################################################
# Si le terminal est terminator
- name: install terminator
  include: terminal/install_terminator.yml
  when: terminal is defined and terminal=="terminator"

# Si le terminal est xterm
- name: install xterm
  include: terminal/install_xterm.yml
  when: terminal is defined and terminal=="xterm"

###############################################################################
# Screensaver
###############################################################################
# Si le screensaver est xscreensaver
- name: install xscreensaver
  include: screensaver/install_xscreensaver.yml
  when: screensaver is defined and screensaver=="xscreensaver"

# Si le screensaver est i3lock
- name: install i3lock
  include: screensaver/install_i3lock.yml
  when: screensaver is defined and screensaver=="i3lock"

# Si le screensaver est i3lock-fancy
- name: install i3lock-fancy
  include: screensaver/install_i3lock-fancy.yml
  when: screensaver is defined and screensaver=="i3lock-fancy"

###############################################################################
# Display manager
###############################################################################
# Si le display manager est lightdm
- name: install lightdm
  include: display_manager/install_lightdm.yml
  when: display_manager is defined and display_manager=="lightdm"

# Si le display manager est sddm
- name: install sddm
  include: display_manager/install_sddm.yml
  when: display_manager is defined and display_manager=="sddm"

###############################################################################
# Other
###############################################################################
# Login-numlock
- name: activate login numlock
  include: other/login_numlock.yml
  when: login_numlock is defined and login_numlock

# Installation de la liste des packet
- name: install list of package
  include: other/install.yml
  when: install is defined

# Ajout des droits sudo à l'utilisateur
- name: Add sudo  privilege for the user
  include: other/sudo.yml
  when: sudo is defined and (sudo or sudo=="nopasswd")

# Reboot
- name: reboot
  reboot:
  when: reboot is defined and reboot
