---
###############################################################################
# Installation de awesome
###############################################################################
# Installation du paquet
- name: install awesome package
  apt:
    name: awesome
    state: present
    update_cache: yes

# On cree le dossier de configuration de awesome s'il n'existe pas
- name: create awesome configuration directory
  file:
    path: "~{{host_user}}/.config/awesome"
    state: directory
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode: 0700

# On copie le fichier de configuration s'il est passé en argument
- name: copy the configuration file
  copy:
    src: "{{ desktop_manager_conf_file }}"
    dest: "~{{host_user}}/.config/awesome/rc.lua"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0744
  when: desktop_manager_conf_file is defined

# On copie le fichier de configuration de awesome par défaut si le fichier de config n'est pas spécifié
- name: copy the configuration file
  template:
    src: "awesome_config"
    dest: "~{{host_user}}/.config/awesome/rc.lua"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0744
  when: desktop_manager_conf_file is not defined