---
##################################################################
# Installation de i3lock-fancy
##################################################################
# Installation du paquet git
- name: install i3lock package
  apt:
    name: i3lock
    state: present
    update_cache: yes

# Installation du paquet git
- name: install scrot package
  apt:
    name: scrot
    state: present
    update_cache: yes
    
# Telechargement du dossier i3lock-fancy
- name: Cloning i3lock-fancy
  git:
    repo: https://github.com/meskarune/i3lock-fancy.git
    dest: "~{{host_user}}/.i3lock-fancy"
    version: dualmonitors

# On change la propriete du dossier i3lock-fancy
- name: Change owner of i3lock-fancy directory
  file:
    path: "~{{host_user}}/.i3lock-fancy"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    recurse: yes

# Installation de i3lock-fancy
- name: install i3lock-fancy
  make:
    chdir: "~{{host_user}}/.i3lock-fancy"
    target: install

##################################################################
# Installation et configuration de xbindkeys
##################################################################
# On installe le gestionnaire de raccourcie clavier
- name: install xbindkeys
  apt:
    name: xbindkeys
    state: present
    update_cache: yes
  when: screenlocker_shortcut is defined

# On vérifie sur le fichier de configuration existe
- name: check if .xbindkeysrc exist
  file:
    path: ~{{host_user}}/.xbindkeysrc
    owner: "{{host_user}}"
    group: "{{host_user}}"
    state: file
  when: screenlocker_shortcut is defined

# On ajoute la configuration du raccourci
- name: add the shortcut configuration
  lineinfile:
    path: ~{{host_user}}/.xbindkeysrc
    line: "{{ item }}"
  when: screenlocker_shortcut is defined
  loop:
    - '"/usr/bin/i3lock-fancy-dualmonitor"'
    - "{{screenlocker_shortcut}}"

# On ajoute le service xbindkeys
- name: add systemd xbindkeys.service
  template:
    src: "xbindkeys.service"
    dest: "~{{host_user}}/.config/systemd/user/xbindkeys.service"
    owner: "{{host_user}}"
    group: "{{host_user}}"
    mode : 0744
  when: screenlocker_shortcut is defined

# On enable le service xbindkeys
- name: enable xbindkeys.service
  systemd:
    name: xbindkeys.service
    enabled: True
    user: "{{host_user}}"
  become: yes
  become_user: "{{host_user}}"
  when: screenlocker_shortcut is defined
